spring:
  application:
    name: hodolog
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지가 0이 아닌 1부터 시작
        default-page-size: 5
server:
  port: 8080
